/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface QueryStrings {}
}

declare global {


  interface HTMLQueryStringsElement extends Components.QueryStrings, HTMLStencilElement {}
  var HTMLQueryStringsElement: {
    prototype: HTMLQueryStringsElement;
    new (): HTMLQueryStringsElement;
  };
  interface HTMLElementTagNameMap {
    'query-strings': HTMLQueryStringsElement;
  }
}

declare namespace LocalJSX {
  interface QueryStrings {}

  interface IntrinsicElements {
    'query-strings': QueryStrings;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'query-strings': LocalJSX.QueryStrings & JSXBase.HTMLAttributes<HTMLQueryStringsElement>;
    }
  }
}


